Add concrete5 9.1.0
concrete5-community/docker5 pull request #22
Opened 2022-05-18 11:24 UTC by 1stthomas

Add latest release.

2022-05-18 12:01 UTC, mlocati requested changes

2022-05-18 12:01 UTC, mlocati commented on .github/workflows/build.yml
> -            additional_tags: "9-full 9.0-full latest-full"
I'd keep the `9.0-full` additional tag...

2022-05-18 12:01 UTC, mlocati commented on .github/workflows/build.yml
> -            additional_tags: "9 9.0 latest"
I'd keep the `9.0` additional tag...

2022-05-21 11:08 UTC, 1stthomas commented
Sorry, missed the re-request review.

2022-05-24 12:42 UTC, mlocati commented
I've restored the 9.0 and 9.0-full tags - see 794a9bd18e200494e9615f21fe536fede3e74e41

2022-05-24 12:51 UTC, mlocati approved these changes

2022-05-24 12:51 UTC, merged